In [32]:
import numpy as np
import scipy.spatial.distance
import re

In [3]:
def readinput(filename):
    out = []
    with open(filename, "r") as fh:
        data = None
        for line in fh:
            line = line.strip()
            if re.match("^---", line):
                if data is not None:
                    out.append(np.array(data, dtype=int))
                data = []
            elif line != "":
                x, y, z = [int(x) for x in line.split(",")]
                data.append([x, y, z])
    out.append(np.array(data, dtype=int))
    return out

test = readinput("test.txt")
test[0]

array([[ 404, -588, -901],
       [ 528, -643,  409],
       [-838,  591,  734],
       [ 390, -675, -793],
       [-537, -823, -458],
       [-485, -357,  347],
       [-345, -311,  381],
       [-661, -816, -575],
       [-876,  649,  763],
       [-618, -824, -621],
       [ 553,  345, -567],
       [ 474,  580,  667],
       [-447, -329,  318],
       [-584,  868, -557],
       [ 544, -627, -890],
       [ 564,  392, -477],
       [ 455,  729,  728],
       [-892,  524,  684],
       [-689,  845, -530],
       [ 423, -701,  434],
       [   7,  -33,  -71],
       [ 630,  319, -379],
       [ 443,  580,  662],
       [-789,  900, -551],
       [ 459, -707,  401]])

In [15]:
def readrots(filename):
    rots = []
    with open(filename, "r") as fh:
        data = []
        for line in fh:
            line = line.strip()
            if re.match("^#", line):
                continue
            elif line == "":
                rot = np.array(data, dtype=int)
                rots.append(rot)
                data = []
            else:
                data.append(line.split(" "))
        rot = np.array(data, dtype=int)
        rots.append(rot)
    return rots

rots = readrots("rot.txt")
rots

[array([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]),
 array([[ 1,  0,  0],
        [ 0,  0, -1],
        [ 0,  1,  0]]),
 array([[ 1,  0,  0],
        [ 0, -1,  0],
        [ 0,  0, -1]]),
 array([[ 1,  0,  0],
        [ 0,  0,  1],
        [ 0, -1,  0]]),
 array([[ 0, -1,  0],
        [ 1,  0,  0],
        [ 0,  0,  1]]),
 array([[0, 0, 1],
        [1, 0, 0],
        [0, 1, 0]]),
 array([[ 0,  1,  0],
        [ 1,  0,  0],
        [ 0,  0, -1]]),
 array([[ 0,  0, -1],
        [ 1,  0,  0],
        [ 0, -1,  0]]),
 array([[-1,  0,  0],
        [ 0, -1,  0],
        [ 0,  0,  1]]),
 array([[-1,  0,  0],
        [ 0,  0, -1],
        [ 0, -1,  0]]),
 array([[-1,  0,  0],
        [ 0,  1,  0],
        [ 0,  0, -1]]),
 array([[-1,  0,  0],
        [ 0,  0,  1],
        [ 0,  1,  0]]),
 array([[ 0,  1,  0],
        [-1,  0,  0],
        [ 0,  0,  1]]),
 array([[ 0,  0,  1],
        [-1,  0,  0],
        [ 0, -1,  0]]),
 array([[ 0, -1,  0],
        [-1,  0,  0],
        [ 0,  0, -1]])

In [13]:
def readdata(s):
    data = []
    for l in s.split("\n"):
        #print(f"<{l}>")
        if len(l):
            data.append([int(x) for x in l.split(",")])
    return np.array(data, dtype=int)

test1 = readdata("""
-1,-1,1
-2,-2,2
-3,-3,3
-2,-3,1
5,6,-4
8,0,7
""")
test1

array([[-1, -1,  1],
       [-2, -2,  2],
       [-3, -3,  3],
       [-2, -3,  1],
       [ 5,  6, -4],
       [ 8,  0,  7]])

In [16]:
for rot in rots:
    print(test1 @ rot.T)
    print()

[[-1 -1  1]
 [-2 -2  2]
 [-3 -3  3]
 [-2 -3  1]
 [ 5  6 -4]
 [ 8  0  7]]

[[-1 -1 -1]
 [-2 -2 -2]
 [-3 -3 -3]
 [-2 -1 -3]
 [ 5  4  6]
 [ 8 -7  0]]

[[-1  1 -1]
 [-2  2 -2]
 [-3  3 -3]
 [-2  3 -1]
 [ 5 -6  4]
 [ 8  0 -7]]

[[-1  1  1]
 [-2  2  2]
 [-3  3  3]
 [-2  1  3]
 [ 5 -4 -6]
 [ 8  7  0]]

[[ 1 -1  1]
 [ 2 -2  2]
 [ 3 -3  3]
 [ 3 -2  1]
 [-6  5 -4]
 [ 0  8  7]]

[[ 1 -1 -1]
 [ 2 -2 -2]
 [ 3 -3 -3]
 [ 1 -2 -3]
 [-4  5  6]
 [ 7  8  0]]

[[-1 -1 -1]
 [-2 -2 -2]
 [-3 -3 -3]
 [-3 -2 -1]
 [ 6  5  4]
 [ 0  8 -7]]

[[-1 -1  1]
 [-2 -2  2]
 [-3 -3  3]
 [-1 -2  3]
 [ 4  5 -6]
 [-7  8  0]]

[[ 1  1  1]
 [ 2  2  2]
 [ 3  3  3]
 [ 2  3  1]
 [-5 -6 -4]
 [-8  0  7]]

[[ 1 -1  1]
 [ 2 -2  2]
 [ 3 -3  3]
 [ 2 -1  3]
 [-5  4 -6]
 [-8 -7  0]]

[[ 1 -1 -1]
 [ 2 -2 -2]
 [ 3 -3 -3]
 [ 2 -3 -1]
 [-5  6  4]
 [-8  0 -7]]

[[ 1  1 -1]
 [ 2  2 -2]
 [ 3  3 -3]
 [ 2  1 -3]
 [-5 -4  6]
 [-8  7  0]]

[[-1  1  1]
 [-2  2  2]
 [-3  3  3]
 [-3  2  1]
 [ 6 -5 -4]
 [ 0 -8  7]]

[[ 1  1  1]
 [ 2  2  2]
 [ 3  3  3]
 [

In [20]:
s0common = readdata("""
-618,-824,-621
-537,-823,-458
-447,-329,318
404,-588,-901
544,-627,-890
528,-643,409
-661,-816,-575
390,-675,-793
423,-701,434
-345,-311,381
459,-707,401
-485,-357,347
""")
s0common

array([[-618, -824, -621],
       [-537, -823, -458],
       [-447, -329,  318],
       [ 404, -588, -901],
       [ 544, -627, -890],
       [ 528, -643,  409],
       [-661, -816, -575],
       [ 390, -675, -793],
       [ 423, -701,  434],
       [-345, -311,  381],
       [ 459, -707,  401],
       [-485, -357,  347]])

In [21]:
s1common = readdata("""
686,422,578
605,423,415
515,917,-361
-336,658,858
-476,619,847
-460,603,-452
729,430,532
-322,571,750
-355,545,-477
413,935,-424
-391,539,-444
553,889,-390
""")
s1common

array([[ 686,  422,  578],
       [ 605,  423,  415],
       [ 515,  917, -361],
       [-336,  658,  858],
       [-476,  619,  847],
       [-460,  603, -452],
       [ 729,  430,  532],
       [-322,  571,  750],
       [-355,  545, -477],
       [ 413,  935, -424],
       [-391,  539, -444],
       [ 553,  889, -390]])

In [28]:
for rot in rots:
    a = s0common - (s1common @ rot.T)
    print(a)
    print(np.max(a, axis=0))
    print(np.min(a, axis=0))
    print()

[[-1304 -1246 -1199]
 [-1142 -1246  -873]
 [ -962 -1246   679]
 [  740 -1246 -1759]
 [ 1020 -1246 -1737]
 [  988 -1246   861]
 [-1390 -1246 -1107]
 [  712 -1246 -1543]
 [  778 -1246   911]
 [ -758 -1246   805]
 [  850 -1246   845]
 [-1038 -1246   737]]
[ 1020 -1246   911]
[-1390 -1246 -1759]

[[-1304  -246 -1043]
 [-1142  -408  -881]
 [ -962  -690  -599]
 [  740   270 -1559]
 [ 1020   220 -1509]
 [  988 -1095  -194]
 [-1390  -284 -1005]
 [  712    75 -1364]
 [  778 -1178  -111]
 [ -758  -735  -554]
 [  850 -1151  -138]
 [-1038  -747  -542]]
[1020  270 -111]
[-1390 -1178 -1559]

[[-1304  -402   -43]
 [-1142  -400   -43]
 [ -962   588   -43]
 [  740    70   -43]
 [ 1020    -8   -43]
 [  988   -40   -43]
 [-1390  -386   -43]
 [  712  -104   -43]
 [  778  -156   -43]
 [ -758   624   -43]
 [  850  -168   -43]
 [-1038   532   -43]]
[1020  624  -43]
[-1390  -402   -43]

[[-1304 -1402  -199]
 [-1142 -1238   -35]
 [ -962    32  1235]
 [  740 -1446  -243]
 [ 1020 -1474  -271]
 [  988  -191  1012

In [66]:
def build_distances(sensor):
    dist = scipy.spatial.distance.cdist(sensor, sensor, 'cityblock').astype(int)
    return [set(d[0]) for d in np.split(dist, len(dist))]

def build_beacon_map(si, sj, dists):
    out = {}
    for bi, disti in enumerate(dists[si]):
        for bj, distj in enumerate(dists[sj]):
            distinter = disti & distj
            if len(distinter) > 10:
                out[bi] = bj
    return out

def build_map(xs):
    dists = [build_distances(x) for x in xs]
    
    smap = dict()
    
    for si in range(len(xs)):
        smap[si] = dict()
        for sj in range(len(xs)):
            if si == sj:
                continue
            m = build_map(si, sj, dists)
            if m:
                smap[si][sj] = m
    return smap
    #print(si, sj, build_map(si, sj, dists))
            
find_common(test)

{0: {1: {0: 3,
   1: 8,
   3: 12,
   4: 1,
   5: 24,
   6: 18,
   7: 10,
   9: 0,
   12: 2,
   14: 5,
   19: 15,
   24: 19}},
 1: {0: {0: 9,
   1: 4,
   2: 12,
   3: 0,
   5: 14,
   8: 1,
   10: 7,
   12: 3,
   15: 19,
   18: 6,
   19: 24,
   24: 5},
  3: {6: 2,
   7: 13,
   9: 20,
   11: 3,
   13: 6,
   14: 0,
   16: 11,
   17: 5,
   20: 17,
   21: 12,
   22: 21,
   23: 24},
  4: {2: 4,
   6: 11,
   8: 24,
   13: 1,
   15: 18,
   16: 15,
   18: 17,
   19: 5,
   21: 13,
   22: 12,
   23: 16,
   24: 3}},
 2: {4: {0: 14,
   1: 18,
   7: 23,
   8: 22,
   11: 11,
   12: 19,
   13: 6,
   16: 1,
   19: 5,
   20: 7,
   23: 13,
   25: 24}},
 3: {1: {0: 14,
   2: 6,
   3: 11,
   5: 17,
   6: 13,
   11: 16,
   12: 21,
   13: 7,
   17: 20,
   20: 9,
   21: 22,
   24: 23}},
 4: {1: {1: 13,
   3: 24,
   4: 2,
   5: 19,
   11: 6,
   12: 22,
   13: 21,
   15: 16,
   16: 23,
   17: 18,
   18: 15,
   24: 8},
  2: {1: 16,
   5: 19,
   6: 13,
   7: 20,
   11: 11,
   13: 23,
   14: 0,
   18: 1,
   19: 12,

In [38]:
Out[36].dtype

dtype('float64')

In [ ]:
scipy.spatial