In [1]:
import numpy as np

In [2]:
def readlines(filename):
    d = []
    with open(filename, "r") as fh:
        for l in fh:
            d.append(l.strip())
    return d
            
test = readlines("test.txt")
test

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 '8  2 23  4 24',
 '21  9 14 16  7',
 '6 10  3 18  5',
 '1 12 20 15 19',
 '',
 '3 15  0  2 22',
 '9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 '2  0 12  3  7']

In [3]:
def splitlist(xs, sep):
    out = [[]]
    for x in xs:
        if x == sep:
            out.append([])
        else:
            out[-1].append(x)
    return out

splitlist(test, "")

[['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1'],
 ['22 13 17 11  0',
  '8  2 23  4 24',
  '21  9 14 16  7',
  '6 10  3 18  5',
  '1 12 20 15 19'],
 ['3 15  0  2 22',
  '9 18 13 17  5',
  '19  8  7 25 23',
  '20 11 10 24  4',
  '14 21 16 12  6'],
 ['14 21 17 24  4',
  '10 16 15  9 19',
  '18  8 23 26 20',
  '22 11 13  6  5',
  '2  0 12  3  7']]

In [4]:
def readmatrix(rows):
    out = []
    for row in rows:
        out.append([int(x) for x in row.split()])
    return np.array(out)

m1 = readmatrix(splitlist(test, "")[1])
print(m1)
print(m1[1,0])
print(m1[0,1])
print(m1[1,:])
print(m1[:,1])
print(m1.shape)

[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
8
13
[ 8  2 23  4 24]
[13  2  9 10 12]
(5, 5)


In [64]:
class Board:
    def __init__(self, rows):
        self.board = self.__read_board(rows)
        self.marks = np.ones(shape=self.board.shape, dtype=int)
        
    def __read_board(self, rows):
        out = []
        for row in rows:
            out.append([int(x) for x in row.split()])
        return np.array(out)

    def mark(self, n):
        self.marks[np.where(self.board == n)] = 0
    
    def check_bingo(self):
        lines = [sum(self.marks[j,:]) for j in range(5)] + [sum(self.marks[:,i]) for i in range(5)]
        if 0 in lines:
            return True
        else:
            return False
    
    def unmarked(self):
        return self.marks * self.board
        
m1 = Board(splitlist(test, "")[1])
print(m1.board)
print(m1.marks)
print(m1.check_bingo())
m1.mark(22)
m1.mark(13)
m1.mark(17)
m1.mark(11)
m1.mark(0)
print(m1.marks)
print(m1.check_bingo())
print(m1.unmarked())

TypeError: 'BingoGame' object is not iterable

In [62]:
class BingoGame:
    def __init__(self, filename):
        data = splitlist(readlines(filename), "")
        self.numbers = [int(x) for x in data[0][0].split(",")]
        self.boards = []
        for b in data[1:]:
            self.boards.append(Board(b))
            
    def play(self):
        for n in self.numbers:
            for b in self.boards:
                b.mark(n)
                #print(b.marks)
                if b.check_bingo():
                    print(b.unmarked())
                    return n * np.sum(b.unmarked())
    
    def play2(self):
        left = [x for x in range(len(self.boards))]
        for n in self.numbers:
            for i, b in enumerate(self.boards):
                if i in left:
                    b.mark(n)
                    if b.check_bingo():
                        if len(left) == 1:
                            last = b.unmarked()
                            print(last)
                            return n * np.sum(last)
                        else:
                            left.remove(i)

test = BingoGame("test.txt")
print(test.numbers)
for b in test.boards:
    print(b.board) 
test.play2()

[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]
[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
[[ 3 15  0  0 22]
 [ 0 18  0  0  0]
 [19  8  0 25  0]
 [20  0  0  0  0]
 [ 0  0  0 12  6]]


1924

In [53]:
inp = BingoGame("input.txt")
inp.play()

[[ 0  0  0  0  0]
 [27 29 22  0 76]
 [58 54 80  0  0]
 [ 0 24 83  0 25]
 [21 31 48 39  4]]


58374

In [63]:
inp = BingoGame("input.txt")
inp.play2()

[[ 0 99  0  0  0]
 [ 0 30 10  0  0]
 [98  0  0  0 25]
 [76  0 29  0  0]
 [ 0  0  0  0  0]]


11377