In [1]:
import numpy as np

In [5]:
def readlines(filename):
    d = []
    with open(filename, "r") as fh:
        for l in fh:
            d.append(l.strip())
    return d
            
test = readlines("test.txt")
test

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 '8  2 23  4 24',
 '21  9 14 16  7',
 '6 10  3 18  5',
 '1 12 20 15 19',
 '',
 '3 15  0  2 22',
 '9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 '2  0 12  3  7']

In [6]:
def splitlist(xs, sep):
    out = [[]]
    for x in xs:
        if x == sep:
            out.append([])
        else:
            out[-1].append(x)
    return out

splitlist(test, "")

[['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1'],
 ['22 13 17 11  0',
  '8  2 23  4 24',
  '21  9 14 16  7',
  '6 10  3 18  5',
  '1 12 20 15 19'],
 ['3 15  0  2 22',
  '9 18 13 17  5',
  '19  8  7 25 23',
  '20 11 10 24  4',
  '14 21 16 12  6'],
 ['14 21 17 24  4',
  '10 16 15  9 19',
  '18  8 23 26 20',
  '22 11 13  6  5',
  '2  0 12  3  7']]

In [19]:
def readmatrix(rows):
    out = []
    for row in rows:
        out.append([int(x) for x in row.split()])
    return np.array(out)

m1 = readmatrix(splitlist(test, "")[1])
print(m1)
print(m1[1,0])
print(m1[0,1])
print(m1[1,:])
print(m1[:,1])
print(m1.shape)

[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
8
13
[ 8  2 23  4 24]
[13  2  9 10 12]
(5, 5)
